[build-system]
requires = ["flit_core >=3.2,<4","myst-parser"]
build-backend = "flit_core.buildapi"

[project]
name = "EasyPoi "
authors = [{name = "夜雨微寒", email = "951683309@qq.com"}]
dynamic = ["version", "description"]
