[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "easypoi"
authors = [{name = "soaringsoul", email = "951683309@qq.com"}]
dynamic = ["version", "description"]
